// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package pbapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PK_KEEPALIVE_REQ_CMD_KEEPALIVE_REQ int32

const (
	PK_KEEPALIVE_REQ_UNKNOWN PK_KEEPALIVE_REQ_CMD_KEEPALIVE_REQ = 0
	PK_KEEPALIVE_REQ_CMD     PK_KEEPALIVE_REQ_CMD_KEEPALIVE_REQ = 168493057
)

var PK_KEEPALIVE_REQ_CMD_KEEPALIVE_REQ_name = map[int32]string{
	0:         "UNKNOWN",
	168493057: "CMD",
}

var PK_KEEPALIVE_REQ_CMD_KEEPALIVE_REQ_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     168493057,
}

func (x PK_KEEPALIVE_REQ_CMD_KEEPALIVE_REQ) String() string {
	return proto.EnumName(PK_KEEPALIVE_REQ_CMD_KEEPALIVE_REQ_name, int32(x))
}

func (PK_KEEPALIVE_REQ_CMD_KEEPALIVE_REQ) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0, 0}
}

type PK_KEEPALIVE_RSP_CMD_KEEPALIVE_RSP int32

const (
	PK_KEEPALIVE_RSP_UNKNOWN PK_KEEPALIVE_RSP_CMD_KEEPALIVE_RSP = 0
	PK_KEEPALIVE_RSP_CMD     PK_KEEPALIVE_RSP_CMD_KEEPALIVE_RSP = 185204737
)

var PK_KEEPALIVE_RSP_CMD_KEEPALIVE_RSP_name = map[int32]string{
	0:         "UNKNOWN",
	185204737: "CMD",
}

var PK_KEEPALIVE_RSP_CMD_KEEPALIVE_RSP_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     185204737,
}

func (x PK_KEEPALIVE_RSP_CMD_KEEPALIVE_RSP) String() string {
	return proto.EnumName(PK_KEEPALIVE_RSP_CMD_KEEPALIVE_RSP_name, int32(x))
}

func (PK_KEEPALIVE_RSP_CMD_KEEPALIVE_RSP) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1, 0}
}

type PK_USER_LOGIN_REQ_CMD_USER_LOGIN_REQ int32

const (
	PK_USER_LOGIN_REQ_UNKNOWN PK_USER_LOGIN_REQ_CMD_USER_LOGIN_REQ = 0
	PK_USER_LOGIN_REQ_CMD     PK_USER_LOGIN_REQ_CMD_USER_LOGIN_REQ = 168493058
)

var PK_USER_LOGIN_REQ_CMD_USER_LOGIN_REQ_name = map[int32]string{
	0:         "UNKNOWN",
	168493058: "CMD",
}

var PK_USER_LOGIN_REQ_CMD_USER_LOGIN_REQ_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     168493058,
}

func (x PK_USER_LOGIN_REQ_CMD_USER_LOGIN_REQ) String() string {
	return proto.EnumName(PK_USER_LOGIN_REQ_CMD_USER_LOGIN_REQ_name, int32(x))
}

func (PK_USER_LOGIN_REQ_CMD_USER_LOGIN_REQ) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2, 0}
}

type PK_USER_LOGIN_RSP_CMD_USER_LOGIN_RSP int32

const (
	PK_USER_LOGIN_RSP_UNKNOWN PK_USER_LOGIN_RSP_CMD_USER_LOGIN_RSP = 0
	PK_USER_LOGIN_RSP_CMD     PK_USER_LOGIN_RSP_CMD_USER_LOGIN_RSP = 185204738
)

var PK_USER_LOGIN_RSP_CMD_USER_LOGIN_RSP_name = map[int32]string{
	0:         "UNKNOWN",
	185204738: "CMD",
}

var PK_USER_LOGIN_RSP_CMD_USER_LOGIN_RSP_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     185204738,
}

func (x PK_USER_LOGIN_RSP_CMD_USER_LOGIN_RSP) String() string {
	return proto.EnumName(PK_USER_LOGIN_RSP_CMD_USER_LOGIN_RSP_name, int32(x))
}

func (PK_USER_LOGIN_RSP_CMD_USER_LOGIN_RSP) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3, 0}
}

type PK_GET_ALL_TABNAMES_REQ_CMD_GET_ALL_TABNAMES_REQ int32

const (
	PK_GET_ALL_TABNAMES_REQ_UNKNOWN PK_GET_ALL_TABNAMES_REQ_CMD_GET_ALL_TABNAMES_REQ = 0
	PK_GET_ALL_TABNAMES_REQ_CMD     PK_GET_ALL_TABNAMES_REQ_CMD_GET_ALL_TABNAMES_REQ = 168493059
)

var PK_GET_ALL_TABNAMES_REQ_CMD_GET_ALL_TABNAMES_REQ_name = map[int32]string{
	0:         "UNKNOWN",
	168493059: "CMD",
}

var PK_GET_ALL_TABNAMES_REQ_CMD_GET_ALL_TABNAMES_REQ_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     168493059,
}

func (x PK_GET_ALL_TABNAMES_REQ_CMD_GET_ALL_TABNAMES_REQ) String() string {
	return proto.EnumName(PK_GET_ALL_TABNAMES_REQ_CMD_GET_ALL_TABNAMES_REQ_name, int32(x))
}

func (PK_GET_ALL_TABNAMES_REQ_CMD_GET_ALL_TABNAMES_REQ) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4, 0}
}

type PK_GET_ALL_TABNAMES_RSP_CMD_GET_ALL_TABNAMES_RSP int32

const (
	PK_GET_ALL_TABNAMES_RSP_UNKNOWN PK_GET_ALL_TABNAMES_RSP_CMD_GET_ALL_TABNAMES_RSP = 0
	PK_GET_ALL_TABNAMES_RSP_CMD     PK_GET_ALL_TABNAMES_RSP_CMD_GET_ALL_TABNAMES_RSP = 185204739
)

var PK_GET_ALL_TABNAMES_RSP_CMD_GET_ALL_TABNAMES_RSP_name = map[int32]string{
	0:         "UNKNOWN",
	185204739: "CMD",
}

var PK_GET_ALL_TABNAMES_RSP_CMD_GET_ALL_TABNAMES_RSP_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     185204739,
}

func (x PK_GET_ALL_TABNAMES_RSP_CMD_GET_ALL_TABNAMES_RSP) String() string {
	return proto.EnumName(PK_GET_ALL_TABNAMES_RSP_CMD_GET_ALL_TABNAMES_RSP_name, int32(x))
}

func (PK_GET_ALL_TABNAMES_RSP_CMD_GET_ALL_TABNAMES_RSP) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5, 0}
}

type PK_OPEN_DB_REQ_CMD_OPEN_DB_REQ int32

const (
	PK_OPEN_DB_REQ_UNKNOWN PK_OPEN_DB_REQ_CMD_OPEN_DB_REQ = 0
	PK_OPEN_DB_REQ_CMD     PK_OPEN_DB_REQ_CMD_OPEN_DB_REQ = 168493061
)

var PK_OPEN_DB_REQ_CMD_OPEN_DB_REQ_name = map[int32]string{
	0:         "UNKNOWN",
	168493061: "CMD",
}

var PK_OPEN_DB_REQ_CMD_OPEN_DB_REQ_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     168493061,
}

func (x PK_OPEN_DB_REQ_CMD_OPEN_DB_REQ) String() string {
	return proto.EnumName(PK_OPEN_DB_REQ_CMD_OPEN_DB_REQ_name, int32(x))
}

func (PK_OPEN_DB_REQ_CMD_OPEN_DB_REQ) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6, 0}
}

type PK_OPEN_DB_RSP_CMD_OPEN_DB_RSP int32

const (
	PK_OPEN_DB_RSP_UNKNOWN PK_OPEN_DB_RSP_CMD_OPEN_DB_RSP = 0
	PK_OPEN_DB_RSP_CMD     PK_OPEN_DB_RSP_CMD_OPEN_DB_RSP = 185204741
)

var PK_OPEN_DB_RSP_CMD_OPEN_DB_RSP_name = map[int32]string{
	0:         "UNKNOWN",
	185204741: "CMD",
}

var PK_OPEN_DB_RSP_CMD_OPEN_DB_RSP_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     185204741,
}

func (x PK_OPEN_DB_RSP_CMD_OPEN_DB_RSP) String() string {
	return proto.EnumName(PK_OPEN_DB_RSP_CMD_OPEN_DB_RSP_name, int32(x))
}

func (PK_OPEN_DB_RSP_CMD_OPEN_DB_RSP) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7, 0}
}

type PK_GET_TABNAMES_PAGE_REQ_CMD_GET_TABNAMES_PAGE_REQ int32

const (
	PK_GET_TABNAMES_PAGE_REQ_UNKNOWN PK_GET_TABNAMES_PAGE_REQ_CMD_GET_TABNAMES_PAGE_REQ = 0
	PK_GET_TABNAMES_PAGE_REQ_CMD     PK_GET_TABNAMES_PAGE_REQ_CMD_GET_TABNAMES_PAGE_REQ = 168493062
)

var PK_GET_TABNAMES_PAGE_REQ_CMD_GET_TABNAMES_PAGE_REQ_name = map[int32]string{
	0:         "UNKNOWN",
	168493062: "CMD",
}

var PK_GET_TABNAMES_PAGE_REQ_CMD_GET_TABNAMES_PAGE_REQ_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     168493062,
}

func (x PK_GET_TABNAMES_PAGE_REQ_CMD_GET_TABNAMES_PAGE_REQ) String() string {
	return proto.EnumName(PK_GET_TABNAMES_PAGE_REQ_CMD_GET_TABNAMES_PAGE_REQ_name, int32(x))
}

func (PK_GET_TABNAMES_PAGE_REQ_CMD_GET_TABNAMES_PAGE_REQ) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8, 0}
}

type PK_GET_TABNAMES_PAGE_RSP_CMD_GET_TABNAMES_PAGE_RSP int32

const (
	PK_GET_TABNAMES_PAGE_RSP_UNKNOWN PK_GET_TABNAMES_PAGE_RSP_CMD_GET_TABNAMES_PAGE_RSP = 0
	PK_GET_TABNAMES_PAGE_RSP_CMD     PK_GET_TABNAMES_PAGE_RSP_CMD_GET_TABNAMES_PAGE_RSP = 185204742
)

var PK_GET_TABNAMES_PAGE_RSP_CMD_GET_TABNAMES_PAGE_RSP_name = map[int32]string{
	0:         "UNKNOWN",
	185204742: "CMD",
}

var PK_GET_TABNAMES_PAGE_RSP_CMD_GET_TABNAMES_PAGE_RSP_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     185204742,
}

func (x PK_GET_TABNAMES_PAGE_RSP_CMD_GET_TABNAMES_PAGE_RSP) String() string {
	return proto.EnumName(PK_GET_TABNAMES_PAGE_RSP_CMD_GET_TABNAMES_PAGE_RSP_name, int32(x))
}

func (PK_GET_TABNAMES_PAGE_RSP_CMD_GET_TABNAMES_PAGE_RSP) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9, 0}
}

type PK_GET_TAB_SQL_REQ_CMD_GET_TAB_SQL_REQ int32

const (
	PK_GET_TAB_SQL_REQ_UNKNOWN PK_GET_TAB_SQL_REQ_CMD_GET_TAB_SQL_REQ = 0
	PK_GET_TAB_SQL_REQ_CMD     PK_GET_TAB_SQL_REQ_CMD_GET_TAB_SQL_REQ = 168493063
)

var PK_GET_TAB_SQL_REQ_CMD_GET_TAB_SQL_REQ_name = map[int32]string{
	0:         "UNKNOWN",
	168493063: "CMD",
}

var PK_GET_TAB_SQL_REQ_CMD_GET_TAB_SQL_REQ_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     168493063,
}

func (x PK_GET_TAB_SQL_REQ_CMD_GET_TAB_SQL_REQ) String() string {
	return proto.EnumName(PK_GET_TAB_SQL_REQ_CMD_GET_TAB_SQL_REQ_name, int32(x))
}

func (PK_GET_TAB_SQL_REQ_CMD_GET_TAB_SQL_REQ) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10, 0}
}

type PK_GET_TAB_SQL_RSP_CMD_GET_TAB_SQL_RSP int32

const (
	PK_GET_TAB_SQL_RSP_UNKNOWN PK_GET_TAB_SQL_RSP_CMD_GET_TAB_SQL_RSP = 0
	PK_GET_TAB_SQL_RSP_CMD     PK_GET_TAB_SQL_RSP_CMD_GET_TAB_SQL_RSP = 185204743
)

var PK_GET_TAB_SQL_RSP_CMD_GET_TAB_SQL_RSP_name = map[int32]string{
	0:         "UNKNOWN",
	185204743: "CMD",
}

var PK_GET_TAB_SQL_RSP_CMD_GET_TAB_SQL_RSP_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     185204743,
}

func (x PK_GET_TAB_SQL_RSP_CMD_GET_TAB_SQL_RSP) String() string {
	return proto.EnumName(PK_GET_TAB_SQL_RSP_CMD_GET_TAB_SQL_RSP_name, int32(x))
}

func (PK_GET_TAB_SQL_RSP_CMD_GET_TAB_SQL_RSP) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11, 0}
}

type PK_GET_TAB_MODEL_CODE_REQ_CMD_GET_TAB_MODEL_CODE_REQ int32

const (
	PK_GET_TAB_MODEL_CODE_REQ_UNKNOWN PK_GET_TAB_MODEL_CODE_REQ_CMD_GET_TAB_MODEL_CODE_REQ = 0
	PK_GET_TAB_MODEL_CODE_REQ_CMD     PK_GET_TAB_MODEL_CODE_REQ_CMD_GET_TAB_MODEL_CODE_REQ = 168493064
)

var PK_GET_TAB_MODEL_CODE_REQ_CMD_GET_TAB_MODEL_CODE_REQ_name = map[int32]string{
	0:         "UNKNOWN",
	168493064: "CMD",
}

var PK_GET_TAB_MODEL_CODE_REQ_CMD_GET_TAB_MODEL_CODE_REQ_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     168493064,
}

func (x PK_GET_TAB_MODEL_CODE_REQ_CMD_GET_TAB_MODEL_CODE_REQ) String() string {
	return proto.EnumName(PK_GET_TAB_MODEL_CODE_REQ_CMD_GET_TAB_MODEL_CODE_REQ_name, int32(x))
}

func (PK_GET_TAB_MODEL_CODE_REQ_CMD_GET_TAB_MODEL_CODE_REQ) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12, 0}
}

type PK_GET_TAB_MODEL_CODE_RSP_CMD_GET_TAB_MODEL_CODE_RSP int32

const (
	PK_GET_TAB_MODEL_CODE_RSP_UNKNOWN PK_GET_TAB_MODEL_CODE_RSP_CMD_GET_TAB_MODEL_CODE_RSP = 0
	PK_GET_TAB_MODEL_CODE_RSP_CMD     PK_GET_TAB_MODEL_CODE_RSP_CMD_GET_TAB_MODEL_CODE_RSP = 185204744
)

var PK_GET_TAB_MODEL_CODE_RSP_CMD_GET_TAB_MODEL_CODE_RSP_name = map[int32]string{
	0:         "UNKNOWN",
	185204744: "CMD",
}

var PK_GET_TAB_MODEL_CODE_RSP_CMD_GET_TAB_MODEL_CODE_RSP_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     185204744,
}

func (x PK_GET_TAB_MODEL_CODE_RSP_CMD_GET_TAB_MODEL_CODE_RSP) String() string {
	return proto.EnumName(PK_GET_TAB_MODEL_CODE_RSP_CMD_GET_TAB_MODEL_CODE_RSP_name, int32(x))
}

func (PK_GET_TAB_MODEL_CODE_RSP_CMD_GET_TAB_MODEL_CODE_RSP) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13, 0}
}

type PK_SET_LOG_DIR_REQ_CMD_SET_LOG_DIR_REQ int32

const (
	PK_SET_LOG_DIR_REQ_UNKNOWN PK_SET_LOG_DIR_REQ_CMD_SET_LOG_DIR_REQ = 0
	PK_SET_LOG_DIR_REQ_CMD     PK_SET_LOG_DIR_REQ_CMD_SET_LOG_DIR_REQ = 168493066
)

var PK_SET_LOG_DIR_REQ_CMD_SET_LOG_DIR_REQ_name = map[int32]string{
	0:         "UNKNOWN",
	168493066: "CMD",
}

var PK_SET_LOG_DIR_REQ_CMD_SET_LOG_DIR_REQ_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     168493066,
}

func (x PK_SET_LOG_DIR_REQ_CMD_SET_LOG_DIR_REQ) String() string {
	return proto.EnumName(PK_SET_LOG_DIR_REQ_CMD_SET_LOG_DIR_REQ_name, int32(x))
}

func (PK_SET_LOG_DIR_REQ_CMD_SET_LOG_DIR_REQ) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14, 0}
}

type PK_SET_LOG_DIR_RSP_CMD_SET_LOG_DIR_RSP int32

const (
	PK_SET_LOG_DIR_RSP_UNKNOWN PK_SET_LOG_DIR_RSP_CMD_SET_LOG_DIR_RSP = 0
	PK_SET_LOG_DIR_RSP_CMD     PK_SET_LOG_DIR_RSP_CMD_SET_LOG_DIR_RSP = 185204746
)

var PK_SET_LOG_DIR_RSP_CMD_SET_LOG_DIR_RSP_name = map[int32]string{
	0:         "UNKNOWN",
	185204746: "CMD",
}

var PK_SET_LOG_DIR_RSP_CMD_SET_LOG_DIR_RSP_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     185204746,
}

func (x PK_SET_LOG_DIR_RSP_CMD_SET_LOG_DIR_RSP) String() string {
	return proto.EnumName(PK_SET_LOG_DIR_RSP_CMD_SET_LOG_DIR_RSP_name, int32(x))
}

func (PK_SET_LOG_DIR_RSP_CMD_SET_LOG_DIR_RSP) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15, 0}
}

// 心跳包:客户端 --> 服务器
type PK_KEEPALIVE_REQ struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_KEEPALIVE_REQ) Reset()         { *m = PK_KEEPALIVE_REQ{} }
func (m *PK_KEEPALIVE_REQ) String() string { return proto.CompactTextString(m) }
func (*PK_KEEPALIVE_REQ) ProtoMessage()    {}
func (*PK_KEEPALIVE_REQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *PK_KEEPALIVE_REQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_KEEPALIVE_REQ.Unmarshal(m, b)
}
func (m *PK_KEEPALIVE_REQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_KEEPALIVE_REQ.Marshal(b, m, deterministic)
}
func (m *PK_KEEPALIVE_REQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_KEEPALIVE_REQ.Merge(m, src)
}
func (m *PK_KEEPALIVE_REQ) XXX_Size() int {
	return xxx_messageInfo_PK_KEEPALIVE_REQ.Size(m)
}
func (m *PK_KEEPALIVE_REQ) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_KEEPALIVE_REQ.DiscardUnknown(m)
}

var xxx_messageInfo_PK_KEEPALIVE_REQ proto.InternalMessageInfo

type PK_KEEPALIVE_RSP struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_KEEPALIVE_RSP) Reset()         { *m = PK_KEEPALIVE_RSP{} }
func (m *PK_KEEPALIVE_RSP) String() string { return proto.CompactTextString(m) }
func (*PK_KEEPALIVE_RSP) ProtoMessage()    {}
func (*PK_KEEPALIVE_RSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *PK_KEEPALIVE_RSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_KEEPALIVE_RSP.Unmarshal(m, b)
}
func (m *PK_KEEPALIVE_RSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_KEEPALIVE_RSP.Marshal(b, m, deterministic)
}
func (m *PK_KEEPALIVE_RSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_KEEPALIVE_RSP.Merge(m, src)
}
func (m *PK_KEEPALIVE_RSP) XXX_Size() int {
	return xxx_messageInfo_PK_KEEPALIVE_RSP.Size(m)
}
func (m *PK_KEEPALIVE_RSP) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_KEEPALIVE_RSP.DiscardUnknown(m)
}

var xxx_messageInfo_PK_KEEPALIVE_RSP proto.InternalMessageInfo

// 用户登录:客户端 --> 服务器
type PK_USER_LOGIN_REQ struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_USER_LOGIN_REQ) Reset()         { *m = PK_USER_LOGIN_REQ{} }
func (m *PK_USER_LOGIN_REQ) String() string { return proto.CompactTextString(m) }
func (*PK_USER_LOGIN_REQ) ProtoMessage()    {}
func (*PK_USER_LOGIN_REQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *PK_USER_LOGIN_REQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_USER_LOGIN_REQ.Unmarshal(m, b)
}
func (m *PK_USER_LOGIN_REQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_USER_LOGIN_REQ.Marshal(b, m, deterministic)
}
func (m *PK_USER_LOGIN_REQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_USER_LOGIN_REQ.Merge(m, src)
}
func (m *PK_USER_LOGIN_REQ) XXX_Size() int {
	return xxx_messageInfo_PK_USER_LOGIN_REQ.Size(m)
}
func (m *PK_USER_LOGIN_REQ) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_USER_LOGIN_REQ.DiscardUnknown(m)
}

var xxx_messageInfo_PK_USER_LOGIN_REQ proto.InternalMessageInfo

func (m *PK_USER_LOGIN_REQ) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PK_USER_LOGIN_REQ) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

// 用户登录回包:服务器 --> 客户端
type PK_USER_LOGIN_RSP struct {
	ErrMsg               string   `protobuf:"bytes,1,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_USER_LOGIN_RSP) Reset()         { *m = PK_USER_LOGIN_RSP{} }
func (m *PK_USER_LOGIN_RSP) String() string { return proto.CompactTextString(m) }
func (*PK_USER_LOGIN_RSP) ProtoMessage()    {}
func (*PK_USER_LOGIN_RSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *PK_USER_LOGIN_RSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_USER_LOGIN_RSP.Unmarshal(m, b)
}
func (m *PK_USER_LOGIN_RSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_USER_LOGIN_RSP.Marshal(b, m, deterministic)
}
func (m *PK_USER_LOGIN_RSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_USER_LOGIN_RSP.Merge(m, src)
}
func (m *PK_USER_LOGIN_RSP) XXX_Size() int {
	return xxx_messageInfo_PK_USER_LOGIN_RSP.Size(m)
}
func (m *PK_USER_LOGIN_RSP) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_USER_LOGIN_RSP.DiscardUnknown(m)
}

var xxx_messageInfo_PK_USER_LOGIN_RSP proto.InternalMessageInfo

func (m *PK_USER_LOGIN_RSP) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// 获取所有表名:客户端 --> 服务器
type PK_GET_ALL_TABNAMES_REQ struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_GET_ALL_TABNAMES_REQ) Reset()         { *m = PK_GET_ALL_TABNAMES_REQ{} }
func (m *PK_GET_ALL_TABNAMES_REQ) String() string { return proto.CompactTextString(m) }
func (*PK_GET_ALL_TABNAMES_REQ) ProtoMessage()    {}
func (*PK_GET_ALL_TABNAMES_REQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *PK_GET_ALL_TABNAMES_REQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_GET_ALL_TABNAMES_REQ.Unmarshal(m, b)
}
func (m *PK_GET_ALL_TABNAMES_REQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_GET_ALL_TABNAMES_REQ.Marshal(b, m, deterministic)
}
func (m *PK_GET_ALL_TABNAMES_REQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_GET_ALL_TABNAMES_REQ.Merge(m, src)
}
func (m *PK_GET_ALL_TABNAMES_REQ) XXX_Size() int {
	return xxx_messageInfo_PK_GET_ALL_TABNAMES_REQ.Size(m)
}
func (m *PK_GET_ALL_TABNAMES_REQ) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_GET_ALL_TABNAMES_REQ.DiscardUnknown(m)
}

var xxx_messageInfo_PK_GET_ALL_TABNAMES_REQ proto.InternalMessageInfo

// 获取所有表名回包:服务器 --> 客户端
type PK_GET_ALL_TABNAMES_RSP struct {
	Errmsg               string   `protobuf:"bytes,1,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Names                []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	Deses                []string `protobuf:"bytes,3,rep,name=deses,proto3" json:"deses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_GET_ALL_TABNAMES_RSP) Reset()         { *m = PK_GET_ALL_TABNAMES_RSP{} }
func (m *PK_GET_ALL_TABNAMES_RSP) String() string { return proto.CompactTextString(m) }
func (*PK_GET_ALL_TABNAMES_RSP) ProtoMessage()    {}
func (*PK_GET_ALL_TABNAMES_RSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *PK_GET_ALL_TABNAMES_RSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_GET_ALL_TABNAMES_RSP.Unmarshal(m, b)
}
func (m *PK_GET_ALL_TABNAMES_RSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_GET_ALL_TABNAMES_RSP.Marshal(b, m, deterministic)
}
func (m *PK_GET_ALL_TABNAMES_RSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_GET_ALL_TABNAMES_RSP.Merge(m, src)
}
func (m *PK_GET_ALL_TABNAMES_RSP) XXX_Size() int {
	return xxx_messageInfo_PK_GET_ALL_TABNAMES_RSP.Size(m)
}
func (m *PK_GET_ALL_TABNAMES_RSP) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_GET_ALL_TABNAMES_RSP.DiscardUnknown(m)
}

var xxx_messageInfo_PK_GET_ALL_TABNAMES_RSP proto.InternalMessageInfo

func (m *PK_GET_ALL_TABNAMES_RSP) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *PK_GET_ALL_TABNAMES_RSP) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *PK_GET_ALL_TABNAMES_RSP) GetDeses() []string {
	if m != nil {
		return m.Deses
	}
	return nil
}

// 打开数据库连接:客户端 --> 服务器
type PK_OPEN_DB_REQ struct {
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Passwd               string   `protobuf:"bytes,5,opt,name=passwd,proto3" json:"passwd,omitempty"`
	Dbname               string   `protobuf:"bytes,6,opt,name=dbname,proto3" json:"dbname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_OPEN_DB_REQ) Reset()         { *m = PK_OPEN_DB_REQ{} }
func (m *PK_OPEN_DB_REQ) String() string { return proto.CompactTextString(m) }
func (*PK_OPEN_DB_REQ) ProtoMessage()    {}
func (*PK_OPEN_DB_REQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *PK_OPEN_DB_REQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_OPEN_DB_REQ.Unmarshal(m, b)
}
func (m *PK_OPEN_DB_REQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_OPEN_DB_REQ.Marshal(b, m, deterministic)
}
func (m *PK_OPEN_DB_REQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_OPEN_DB_REQ.Merge(m, src)
}
func (m *PK_OPEN_DB_REQ) XXX_Size() int {
	return xxx_messageInfo_PK_OPEN_DB_REQ.Size(m)
}
func (m *PK_OPEN_DB_REQ) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_OPEN_DB_REQ.DiscardUnknown(m)
}

var xxx_messageInfo_PK_OPEN_DB_REQ proto.InternalMessageInfo

func (m *PK_OPEN_DB_REQ) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *PK_OPEN_DB_REQ) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *PK_OPEN_DB_REQ) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PK_OPEN_DB_REQ) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *PK_OPEN_DB_REQ) GetDbname() string {
	if m != nil {
		return m.Dbname
	}
	return ""
}

// 打开数据库连接回包:服务器 --> 客户端
type PK_OPEN_DB_RSP struct {
	Errmsg               string   `protobuf:"bytes,1,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_OPEN_DB_RSP) Reset()         { *m = PK_OPEN_DB_RSP{} }
func (m *PK_OPEN_DB_RSP) String() string { return proto.CompactTextString(m) }
func (*PK_OPEN_DB_RSP) ProtoMessage()    {}
func (*PK_OPEN_DB_RSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *PK_OPEN_DB_RSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_OPEN_DB_RSP.Unmarshal(m, b)
}
func (m *PK_OPEN_DB_RSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_OPEN_DB_RSP.Marshal(b, m, deterministic)
}
func (m *PK_OPEN_DB_RSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_OPEN_DB_RSP.Merge(m, src)
}
func (m *PK_OPEN_DB_RSP) XXX_Size() int {
	return xxx_messageInfo_PK_OPEN_DB_RSP.Size(m)
}
func (m *PK_OPEN_DB_RSP) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_OPEN_DB_RSP.DiscardUnknown(m)
}

var xxx_messageInfo_PK_OPEN_DB_RSP proto.InternalMessageInfo

func (m *PK_OPEN_DB_RSP) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

// 按页获取表名:客户端 --> 服务器
type PK_GET_TABNAMES_PAGE_REQ struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter               string   `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_GET_TABNAMES_PAGE_REQ) Reset()         { *m = PK_GET_TABNAMES_PAGE_REQ{} }
func (m *PK_GET_TABNAMES_PAGE_REQ) String() string { return proto.CompactTextString(m) }
func (*PK_GET_TABNAMES_PAGE_REQ) ProtoMessage()    {}
func (*PK_GET_TABNAMES_PAGE_REQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *PK_GET_TABNAMES_PAGE_REQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_GET_TABNAMES_PAGE_REQ.Unmarshal(m, b)
}
func (m *PK_GET_TABNAMES_PAGE_REQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_GET_TABNAMES_PAGE_REQ.Marshal(b, m, deterministic)
}
func (m *PK_GET_TABNAMES_PAGE_REQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_GET_TABNAMES_PAGE_REQ.Merge(m, src)
}
func (m *PK_GET_TABNAMES_PAGE_REQ) XXX_Size() int {
	return xxx_messageInfo_PK_GET_TABNAMES_PAGE_REQ.Size(m)
}
func (m *PK_GET_TABNAMES_PAGE_REQ) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_GET_TABNAMES_PAGE_REQ.DiscardUnknown(m)
}

var xxx_messageInfo_PK_GET_TABNAMES_PAGE_REQ proto.InternalMessageInfo

func (m *PK_GET_TABNAMES_PAGE_REQ) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PK_GET_TABNAMES_PAGE_REQ) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PK_GET_TABNAMES_PAGE_REQ) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

// 按页获取表名回包:服务器 --> 客户端
type PK_GET_TABNAMES_PAGE_RSP struct {
	Errmsg               string   `protobuf:"bytes,1,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Total                uint32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Names                []string `protobuf:"bytes,3,rep,name=names,proto3" json:"names,omitempty"`
	Deses                []string `protobuf:"bytes,4,rep,name=deses,proto3" json:"deses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_GET_TABNAMES_PAGE_RSP) Reset()         { *m = PK_GET_TABNAMES_PAGE_RSP{} }
func (m *PK_GET_TABNAMES_PAGE_RSP) String() string { return proto.CompactTextString(m) }
func (*PK_GET_TABNAMES_PAGE_RSP) ProtoMessage()    {}
func (*PK_GET_TABNAMES_PAGE_RSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *PK_GET_TABNAMES_PAGE_RSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_GET_TABNAMES_PAGE_RSP.Unmarshal(m, b)
}
func (m *PK_GET_TABNAMES_PAGE_RSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_GET_TABNAMES_PAGE_RSP.Marshal(b, m, deterministic)
}
func (m *PK_GET_TABNAMES_PAGE_RSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_GET_TABNAMES_PAGE_RSP.Merge(m, src)
}
func (m *PK_GET_TABNAMES_PAGE_RSP) XXX_Size() int {
	return xxx_messageInfo_PK_GET_TABNAMES_PAGE_RSP.Size(m)
}
func (m *PK_GET_TABNAMES_PAGE_RSP) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_GET_TABNAMES_PAGE_RSP.DiscardUnknown(m)
}

var xxx_messageInfo_PK_GET_TABNAMES_PAGE_RSP proto.InternalMessageInfo

func (m *PK_GET_TABNAMES_PAGE_RSP) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *PK_GET_TABNAMES_PAGE_RSP) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PK_GET_TABNAMES_PAGE_RSP) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *PK_GET_TABNAMES_PAGE_RSP) GetDeses() []string {
	if m != nil {
		return m.Deses
	}
	return nil
}

// 获取建表sql语句:客户端 --> 服务器
type PK_GET_TAB_SQL_REQ struct {
	Tabname              string   `protobuf:"bytes,1,opt,name=tabname,proto3" json:"tabname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_GET_TAB_SQL_REQ) Reset()         { *m = PK_GET_TAB_SQL_REQ{} }
func (m *PK_GET_TAB_SQL_REQ) String() string { return proto.CompactTextString(m) }
func (*PK_GET_TAB_SQL_REQ) ProtoMessage()    {}
func (*PK_GET_TAB_SQL_REQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *PK_GET_TAB_SQL_REQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_GET_TAB_SQL_REQ.Unmarshal(m, b)
}
func (m *PK_GET_TAB_SQL_REQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_GET_TAB_SQL_REQ.Marshal(b, m, deterministic)
}
func (m *PK_GET_TAB_SQL_REQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_GET_TAB_SQL_REQ.Merge(m, src)
}
func (m *PK_GET_TAB_SQL_REQ) XXX_Size() int {
	return xxx_messageInfo_PK_GET_TAB_SQL_REQ.Size(m)
}
func (m *PK_GET_TAB_SQL_REQ) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_GET_TAB_SQL_REQ.DiscardUnknown(m)
}

var xxx_messageInfo_PK_GET_TAB_SQL_REQ proto.InternalMessageInfo

func (m *PK_GET_TAB_SQL_REQ) GetTabname() string {
	if m != nil {
		return m.Tabname
	}
	return ""
}

// 获取建表sql语句回包:服务器 --> 客户端
type PK_GET_TAB_SQL_RSP struct {
	Errmsg               string   `protobuf:"bytes,1,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Sql                  string   `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_GET_TAB_SQL_RSP) Reset()         { *m = PK_GET_TAB_SQL_RSP{} }
func (m *PK_GET_TAB_SQL_RSP) String() string { return proto.CompactTextString(m) }
func (*PK_GET_TAB_SQL_RSP) ProtoMessage()    {}
func (*PK_GET_TAB_SQL_RSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *PK_GET_TAB_SQL_RSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_GET_TAB_SQL_RSP.Unmarshal(m, b)
}
func (m *PK_GET_TAB_SQL_RSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_GET_TAB_SQL_RSP.Marshal(b, m, deterministic)
}
func (m *PK_GET_TAB_SQL_RSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_GET_TAB_SQL_RSP.Merge(m, src)
}
func (m *PK_GET_TAB_SQL_RSP) XXX_Size() int {
	return xxx_messageInfo_PK_GET_TAB_SQL_RSP.Size(m)
}
func (m *PK_GET_TAB_SQL_RSP) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_GET_TAB_SQL_RSP.DiscardUnknown(m)
}

var xxx_messageInfo_PK_GET_TAB_SQL_RSP proto.InternalMessageInfo

func (m *PK_GET_TAB_SQL_RSP) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *PK_GET_TAB_SQL_RSP) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

// 获取model代码:客户端 --> 服务器
type PK_GET_TAB_MODEL_CODE_REQ struct {
	Tabname              string   `protobuf:"bytes,1,opt,name=tabname,proto3" json:"tabname,omitempty"`
	Prefix               string   `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_GET_TAB_MODEL_CODE_REQ) Reset()         { *m = PK_GET_TAB_MODEL_CODE_REQ{} }
func (m *PK_GET_TAB_MODEL_CODE_REQ) String() string { return proto.CompactTextString(m) }
func (*PK_GET_TAB_MODEL_CODE_REQ) ProtoMessage()    {}
func (*PK_GET_TAB_MODEL_CODE_REQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *PK_GET_TAB_MODEL_CODE_REQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_GET_TAB_MODEL_CODE_REQ.Unmarshal(m, b)
}
func (m *PK_GET_TAB_MODEL_CODE_REQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_GET_TAB_MODEL_CODE_REQ.Marshal(b, m, deterministic)
}
func (m *PK_GET_TAB_MODEL_CODE_REQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_GET_TAB_MODEL_CODE_REQ.Merge(m, src)
}
func (m *PK_GET_TAB_MODEL_CODE_REQ) XXX_Size() int {
	return xxx_messageInfo_PK_GET_TAB_MODEL_CODE_REQ.Size(m)
}
func (m *PK_GET_TAB_MODEL_CODE_REQ) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_GET_TAB_MODEL_CODE_REQ.DiscardUnknown(m)
}

var xxx_messageInfo_PK_GET_TAB_MODEL_CODE_REQ proto.InternalMessageInfo

func (m *PK_GET_TAB_MODEL_CODE_REQ) GetTabname() string {
	if m != nil {
		return m.Tabname
	}
	return ""
}

func (m *PK_GET_TAB_MODEL_CODE_REQ) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

// 获取model代码回包:服务器 --> 客户端
type PK_GET_TAB_MODEL_CODE_RSP struct {
	Errmsg               string   `protobuf:"bytes,1,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_GET_TAB_MODEL_CODE_RSP) Reset()         { *m = PK_GET_TAB_MODEL_CODE_RSP{} }
func (m *PK_GET_TAB_MODEL_CODE_RSP) String() string { return proto.CompactTextString(m) }
func (*PK_GET_TAB_MODEL_CODE_RSP) ProtoMessage()    {}
func (*PK_GET_TAB_MODEL_CODE_RSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *PK_GET_TAB_MODEL_CODE_RSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_GET_TAB_MODEL_CODE_RSP.Unmarshal(m, b)
}
func (m *PK_GET_TAB_MODEL_CODE_RSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_GET_TAB_MODEL_CODE_RSP.Marshal(b, m, deterministic)
}
func (m *PK_GET_TAB_MODEL_CODE_RSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_GET_TAB_MODEL_CODE_RSP.Merge(m, src)
}
func (m *PK_GET_TAB_MODEL_CODE_RSP) XXX_Size() int {
	return xxx_messageInfo_PK_GET_TAB_MODEL_CODE_RSP.Size(m)
}
func (m *PK_GET_TAB_MODEL_CODE_RSP) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_GET_TAB_MODEL_CODE_RSP.DiscardUnknown(m)
}

var xxx_messageInfo_PK_GET_TAB_MODEL_CODE_RSP proto.InternalMessageInfo

func (m *PK_GET_TAB_MODEL_CODE_RSP) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *PK_GET_TAB_MODEL_CODE_RSP) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type PK_SET_LOG_DIR_REQ struct {
	Dir                  string   `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_SET_LOG_DIR_REQ) Reset()         { *m = PK_SET_LOG_DIR_REQ{} }
func (m *PK_SET_LOG_DIR_REQ) String() string { return proto.CompactTextString(m) }
func (*PK_SET_LOG_DIR_REQ) ProtoMessage()    {}
func (*PK_SET_LOG_DIR_REQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *PK_SET_LOG_DIR_REQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_SET_LOG_DIR_REQ.Unmarshal(m, b)
}
func (m *PK_SET_LOG_DIR_REQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_SET_LOG_DIR_REQ.Marshal(b, m, deterministic)
}
func (m *PK_SET_LOG_DIR_REQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_SET_LOG_DIR_REQ.Merge(m, src)
}
func (m *PK_SET_LOG_DIR_REQ) XXX_Size() int {
	return xxx_messageInfo_PK_SET_LOG_DIR_REQ.Size(m)
}
func (m *PK_SET_LOG_DIR_REQ) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_SET_LOG_DIR_REQ.DiscardUnknown(m)
}

var xxx_messageInfo_PK_SET_LOG_DIR_REQ proto.InternalMessageInfo

func (m *PK_SET_LOG_DIR_REQ) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

type PK_SET_LOG_DIR_RSP struct {
	Errmsg               string   `protobuf:"bytes,1,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_SET_LOG_DIR_RSP) Reset()         { *m = PK_SET_LOG_DIR_RSP{} }
func (m *PK_SET_LOG_DIR_RSP) String() string { return proto.CompactTextString(m) }
func (*PK_SET_LOG_DIR_RSP) ProtoMessage()    {}
func (*PK_SET_LOG_DIR_RSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *PK_SET_LOG_DIR_RSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_SET_LOG_DIR_RSP.Unmarshal(m, b)
}
func (m *PK_SET_LOG_DIR_RSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_SET_LOG_DIR_RSP.Marshal(b, m, deterministic)
}
func (m *PK_SET_LOG_DIR_RSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_SET_LOG_DIR_RSP.Merge(m, src)
}
func (m *PK_SET_LOG_DIR_RSP) XXX_Size() int {
	return xxx_messageInfo_PK_SET_LOG_DIR_RSP.Size(m)
}
func (m *PK_SET_LOG_DIR_RSP) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_SET_LOG_DIR_RSP.DiscardUnknown(m)
}

var xxx_messageInfo_PK_SET_LOG_DIR_RSP proto.InternalMessageInfo

func (m *PK_SET_LOG_DIR_RSP) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterEnum("pbapi.PK_KEEPALIVE_REQ_CMD_KEEPALIVE_REQ", PK_KEEPALIVE_REQ_CMD_KEEPALIVE_REQ_name, PK_KEEPALIVE_REQ_CMD_KEEPALIVE_REQ_value)
	proto.RegisterEnum("pbapi.PK_KEEPALIVE_RSP_CMD_KEEPALIVE_RSP", PK_KEEPALIVE_RSP_CMD_KEEPALIVE_RSP_name, PK_KEEPALIVE_RSP_CMD_KEEPALIVE_RSP_value)
	proto.RegisterEnum("pbapi.PK_USER_LOGIN_REQ_CMD_USER_LOGIN_REQ", PK_USER_LOGIN_REQ_CMD_USER_LOGIN_REQ_name, PK_USER_LOGIN_REQ_CMD_USER_LOGIN_REQ_value)
	proto.RegisterEnum("pbapi.PK_USER_LOGIN_RSP_CMD_USER_LOGIN_RSP", PK_USER_LOGIN_RSP_CMD_USER_LOGIN_RSP_name, PK_USER_LOGIN_RSP_CMD_USER_LOGIN_RSP_value)
	proto.RegisterEnum("pbapi.PK_GET_ALL_TABNAMES_REQ_CMD_GET_ALL_TABNAMES_REQ", PK_GET_ALL_TABNAMES_REQ_CMD_GET_ALL_TABNAMES_REQ_name, PK_GET_ALL_TABNAMES_REQ_CMD_GET_ALL_TABNAMES_REQ_value)
	proto.RegisterEnum("pbapi.PK_GET_ALL_TABNAMES_RSP_CMD_GET_ALL_TABNAMES_RSP", PK_GET_ALL_TABNAMES_RSP_CMD_GET_ALL_TABNAMES_RSP_name, PK_GET_ALL_TABNAMES_RSP_CMD_GET_ALL_TABNAMES_RSP_value)
	proto.RegisterEnum("pbapi.PK_OPEN_DB_REQ_CMD_OPEN_DB_REQ", PK_OPEN_DB_REQ_CMD_OPEN_DB_REQ_name, PK_OPEN_DB_REQ_CMD_OPEN_DB_REQ_value)
	proto.RegisterEnum("pbapi.PK_OPEN_DB_RSP_CMD_OPEN_DB_RSP", PK_OPEN_DB_RSP_CMD_OPEN_DB_RSP_name, PK_OPEN_DB_RSP_CMD_OPEN_DB_RSP_value)
	proto.RegisterEnum("pbapi.PK_GET_TABNAMES_PAGE_REQ_CMD_GET_TABNAMES_PAGE_REQ", PK_GET_TABNAMES_PAGE_REQ_CMD_GET_TABNAMES_PAGE_REQ_name, PK_GET_TABNAMES_PAGE_REQ_CMD_GET_TABNAMES_PAGE_REQ_value)
	proto.RegisterEnum("pbapi.PK_GET_TABNAMES_PAGE_RSP_CMD_GET_TABNAMES_PAGE_RSP", PK_GET_TABNAMES_PAGE_RSP_CMD_GET_TABNAMES_PAGE_RSP_name, PK_GET_TABNAMES_PAGE_RSP_CMD_GET_TABNAMES_PAGE_RSP_value)
	proto.RegisterEnum("pbapi.PK_GET_TAB_SQL_REQ_CMD_GET_TAB_SQL_REQ", PK_GET_TAB_SQL_REQ_CMD_GET_TAB_SQL_REQ_name, PK_GET_TAB_SQL_REQ_CMD_GET_TAB_SQL_REQ_value)
	proto.RegisterEnum("pbapi.PK_GET_TAB_SQL_RSP_CMD_GET_TAB_SQL_RSP", PK_GET_TAB_SQL_RSP_CMD_GET_TAB_SQL_RSP_name, PK_GET_TAB_SQL_RSP_CMD_GET_TAB_SQL_RSP_value)
	proto.RegisterEnum("pbapi.PK_GET_TAB_MODEL_CODE_REQ_CMD_GET_TAB_MODEL_CODE_REQ", PK_GET_TAB_MODEL_CODE_REQ_CMD_GET_TAB_MODEL_CODE_REQ_name, PK_GET_TAB_MODEL_CODE_REQ_CMD_GET_TAB_MODEL_CODE_REQ_value)
	proto.RegisterEnum("pbapi.PK_GET_TAB_MODEL_CODE_RSP_CMD_GET_TAB_MODEL_CODE_RSP", PK_GET_TAB_MODEL_CODE_RSP_CMD_GET_TAB_MODEL_CODE_RSP_name, PK_GET_TAB_MODEL_CODE_RSP_CMD_GET_TAB_MODEL_CODE_RSP_value)
	proto.RegisterEnum("pbapi.PK_SET_LOG_DIR_REQ_CMD_SET_LOG_DIR_REQ", PK_SET_LOG_DIR_REQ_CMD_SET_LOG_DIR_REQ_name, PK_SET_LOG_DIR_REQ_CMD_SET_LOG_DIR_REQ_value)
	proto.RegisterEnum("pbapi.PK_SET_LOG_DIR_RSP_CMD_SET_LOG_DIR_RSP", PK_SET_LOG_DIR_RSP_CMD_SET_LOG_DIR_RSP_name, PK_SET_LOG_DIR_RSP_CMD_SET_LOG_DIR_RSP_value)
	proto.RegisterType((*PK_KEEPALIVE_REQ)(nil), "pbapi.PK_KEEPALIVE_REQ")
	proto.RegisterType((*PK_KEEPALIVE_RSP)(nil), "pbapi.PK_KEEPALIVE_RSP")
	proto.RegisterType((*PK_USER_LOGIN_REQ)(nil), "pbapi.PK_USER_LOGIN_REQ")
	proto.RegisterType((*PK_USER_LOGIN_RSP)(nil), "pbapi.PK_USER_LOGIN_RSP")
	proto.RegisterType((*PK_GET_ALL_TABNAMES_REQ)(nil), "pbapi.PK_GET_ALL_TABNAMES_REQ")
	proto.RegisterType((*PK_GET_ALL_TABNAMES_RSP)(nil), "pbapi.PK_GET_ALL_TABNAMES_RSP")
	proto.RegisterType((*PK_OPEN_DB_REQ)(nil), "pbapi.PK_OPEN_DB_REQ")
	proto.RegisterType((*PK_OPEN_DB_RSP)(nil), "pbapi.PK_OPEN_DB_RSP")
	proto.RegisterType((*PK_GET_TABNAMES_PAGE_REQ)(nil), "pbapi.PK_GET_TABNAMES_PAGE_REQ")
	proto.RegisterType((*PK_GET_TABNAMES_PAGE_RSP)(nil), "pbapi.PK_GET_TABNAMES_PAGE_RSP")
	proto.RegisterType((*PK_GET_TAB_SQL_REQ)(nil), "pbapi.PK_GET_TAB_SQL_REQ")
	proto.RegisterType((*PK_GET_TAB_SQL_RSP)(nil), "pbapi.PK_GET_TAB_SQL_RSP")
	proto.RegisterType((*PK_GET_TAB_MODEL_CODE_REQ)(nil), "pbapi.PK_GET_TAB_MODEL_CODE_REQ")
	proto.RegisterType((*PK_GET_TAB_MODEL_CODE_RSP)(nil), "pbapi.PK_GET_TAB_MODEL_CODE_RSP")
	proto.RegisterType((*PK_SET_LOG_DIR_REQ)(nil), "pbapi.PK_SET_LOG_DIR_REQ")
	proto.RegisterType((*PK_SET_LOG_DIR_RSP)(nil), "pbapi.PK_SET_LOG_DIR_RSP")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 637 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xcf, 0x4f, 0x9c, 0x4e,
	0x14, 0xff, 0x22, 0xab, 0x7e, 0xf7, 0x35, 0xb6, 0x2b, 0x6d, 0x5a, 0xf4, 0x64, 0x38, 0x99, 0xa6,
	0xf5, 0x62, 0x7b, 0xef, 0x2a, 0x13, 0x63, 0x60, 0x59, 0x84, 0xd5, 0x9a, 0xa6, 0xe9, 0x84, 0x2d,
	0xb8, 0x92, 0xec, 0x0a, 0x02, 0x8d, 0x3d, 0x35, 0x56, 0xeb, 0x8f, 0x78, 0xf4, 0xaf, 0x30, 0x4d,
	0x0f, 0xfd, 0x13, 0x9b, 0x37, 0xc0, 0x8a, 0x32, 0xc3, 0x6d, 0xde, 0x5b, 0xf8, 0xfc, 0x7a, 0x6f,
	0x58, 0x68, 0x7b, 0x71, 0xb8, 0x16, 0x27, 0x51, 0x16, 0x29, 0xb3, 0xf1, 0xd0, 0x8b, 0x43, 0xed,
	0x03, 0x74, 0x6c, 0x83, 0x1a, 0x84, 0xd8, 0x5d, 0x73, 0x7b, 0x8f, 0x50, 0x87, 0xec, 0x68, 0x6f,
	0x60, 0x71, 0xb3, 0xa7, 0x3f, 0x6c, 0x2a, 0x4f, 0x60, 0x7e, 0xd7, 0x32, 0xac, 0xfe, 0x47, 0xab,
	0xf3, 0x9f, 0x02, 0x20, 0x6f, 0xf6, 0xf4, 0xce, 0xcf, 0xd3, 0x3f, 0x76, 0x1d, 0xc1, 0xb5, 0x39,
	0x08, 0xae, 0x2d, 0x40, 0xb8, 0xdb, 0xd7, 0x0e, 0x61, 0xd1, 0x36, 0xe8, 0xae, 0x4b, 0x1c, 0x6a,
	0xf6, 0xb7, 0xb6, 0x2d, 0xc6, 0xa7, 0x40, 0xeb, 0xc8, 0x9b, 0x04, 0xaa, 0xb4, 0x22, 0xad, 0xb6,
	0x1d, 0x76, 0x56, 0x3a, 0x20, 0xc7, 0x27, 0xbe, 0x3a, 0xc3, 0x5a, 0x78, 0xd4, 0xde, 0x82, 0x82,
	0x44, 0x8f, 0xde, 0xe5, 0x31, 0x9d, 0xa1, 0xd6, 0x4f, 0x35, 0x26, 0xd7, 0x56, 0x5e, 0xc2, 0x5c,
	0x90, 0x24, 0xbd, 0x74, 0x54, 0x70, 0x15, 0x15, 0x0f, 0x5b, 0xe0, 0xe2, 0x0c, 0x5d, 0x58, 0xf0,
	0xca, 0x36, 0xe8, 0x16, 0x19, 0xd0, 0xae, 0x69, 0xd2, 0x41, 0x77, 0xc3, 0xea, 0xf6, 0x88, 0xcb,
	0x02, 0x5d, 0x07, 0x15, 0x91, 0x78, 0xbf, 0x71, 0xf1, 0xce, 0x51, 0xeb, 0xad, 0x24, 0x00, 0x9c,
	0x4a, 0x9e, 0x3c, 0x90, 0x3c, 0x49, 0x47, 0xca, 0x0b, 0x98, 0xc5, 0xa0, 0x52, 0x75, 0x66, 0x45,
	0x5e, 0x6d, 0x3b, 0x79, 0x81, 0x5d, 0x3f, 0x48, 0x83, 0x54, 0x95, 0xf3, 0x2e, 0x2b, 0xc4, 0xa2,
	0x04, 0x26, 0xcf, 0xd1, 0xe4, 0x5f, 0x09, 0x9e, 0xda, 0x06, 0xed, 0xdb, 0xc4, 0xa2, 0xfa, 0x46,
	0x39, 0xa8, 0xc3, 0x28, 0xcd, 0x8a, 0xa9, 0xb0, 0x33, 0xf6, 0xe2, 0x28, 0xc9, 0x54, 0x79, 0x45,
	0x5a, 0x5d, 0x70, 0xd8, 0x59, 0x59, 0x86, 0xff, 0xbf, 0xa5, 0x41, 0xc2, 0x86, 0xda, 0x62, 0xcf,
	0x4e, 0x6b, 0xf4, 0x13, 0x7b, 0x69, 0x7a, 0xe2, 0xab, 0xb3, 0xb9, 0x9f, 0xbc, 0xc2, 0xbe, 0x3f,
	0x64, 0x6f, 0xcc, 0xe5, 0xfd, 0xbc, 0xd2, 0x5e, 0xc3, 0x33, 0xd4, 0x5e, 0x95, 0xc1, 0x93, 0x7c,
	0x81, 0x39, 0x0e, 0x1e, 0x2a, 0x16, 0xa7, 0x57, 0x43, 0x15, 0x04, 0x71, 0x81, 0x41, 0xdc, 0x4a,
	0xa0, 0x16, 0xd3, 0x99, 0x26, 0x67, 0x77, 0xb7, 0x48, 0x19, 0x49, 0xec, 0x8d, 0xf2, 0xdd, 0x45,
	0xfb, 0xde, 0x28, 0xc0, 0x21, 0x8c, 0xc3, 0x49, 0x98, 0xe7, 0xb4, 0xe0, 0xe4, 0x05, 0x4a, 0x39,
	0x08, 0xc7, 0x59, 0x90, 0xb0, 0xa8, 0xda, 0x4e, 0x51, 0x69, 0xef, 0x60, 0xa9, 0x1c, 0x4e, 0x1d,
	0x9e, 0x27, 0xea, 0x12, 0xad, 0xfe, 0x16, 0x8a, 0x6a, 0xde, 0x99, 0x2c, 0xca, 0xbc, 0x71, 0x29,
	0x8c, 0x15, 0xf7, 0x9b, 0x24, 0x73, 0x37, 0xa9, 0x55, 0xdd, 0x24, 0xb1, 0x58, 0x41, 0x82, 0x97,
	0x98, 0xe0, 0x17, 0x50, 0xee, 0xb5, 0x52, 0x77, 0xc7, 0x64, 0xde, 0x54, 0x98, 0xcf, 0xbc, 0x61,
	0xe5, 0xe6, 0x97, 0xa5, 0xb6, 0x06, 0xcf, 0x2b, 0x2c, 0xd3, 0x17, 0x78, 0xf8, 0x57, 0x18, 0xc6,
	0x51, 0x1d, 0xbf, 0x21, 0x85, 0x0e, 0xc8, 0xe9, 0xf1, 0xb8, 0xfc, 0xb4, 0xa4, 0xc7, 0x63, 0x2e,
	0x9f, 0xc0, 0xcf, 0x15, 0xfa, 0xf9, 0x25, 0xc1, 0x52, 0x85, 0xb0, 0xd7, 0xd7, 0x89, 0x49, 0x37,
	0xfb, 0x3a, 0x69, 0xf6, 0xc5, 0x76, 0x3f, 0x09, 0x0e, 0xc2, 0xef, 0x05, 0x79, 0x51, 0x69, 0xef,
	0x61, 0xb9, 0xca, 0xff, 0x08, 0x8f, 0x27, 0xe3, 0x1a, 0x6d, 0xff, 0x10, 0xaa, 0x68, 0x70, 0xaf,
	0x40, 0xeb, 0x6b, 0xe4, 0x07, 0xe5, 0x1d, 0xc6, 0x73, 0x13, 0xbf, 0x20, 0x86, 0x6b, 0x8c, 0x61,
	0x8f, 0xc5, 0xee, 0x92, 0x01, 0x7e, 0x33, 0xa9, 0xbe, 0xed, 0x30, 0xb9, 0x1d, 0x90, 0xfd, 0x30,
	0x29, 0x58, 0xf1, 0x58, 0xc6, 0xfb, 0xf8, 0x41, 0x1e, 0xee, 0x0d, 0xfa, 0xfa, 0x5c, 0xc7, 0x6d,
	0xb8, 0xca, 0x3c, 0x74, 0x81, 0xea, 0x9b, 0xd3, 0xbb, 0xfd, 0xe1, 0x1c, 0xfb, 0x53, 0x5c, 0xff,
	0x17, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xe8, 0x63, 0xe4, 0x21, 0x07, 0x00, 0x00,
}
